### PR TITLE
add testing for problem

### LINKED ISSUE #20: add test + forks
### Comment:

@vsoch I will add a test or two to make sure the problem doesn't happen... weird because we pointed to the same pypi one, so maybe conda-forge's build is missing some piece (in which case we can report it there).

Also, just fyi, when we open branches here in the feedstock, they actually end up publishing to anaconda.org 😅, so the branch you opened to add the deps likely produced some artifacts. Usually it makes no difference if it is a quick thing, but sometimes it can result in some annoying situations were not ready artifacts get published. 

https://github.com/conda-forge/singularity-hpc-feedstock/runs/6415284002

In this case, nothing got up because the content (hashes) didn't change: https://anaconda.org/conda-forge/singularity-hpc/files

### PR DESCRIPTION
**Pull request by ngam**
fixes #20 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@vsoch two things: 
1. I think this resolves the issue, we definitely had the right ruamel.yaml but it was in host not in run for some reason. Being in host means it is available for building but it doesn't get installed at run time (that's what run is for)
2. Would you like me to mark the previous builds as broken or even better retroactively fix the previous builds? We can do that. Just let me know and I will handle the logistics of that.

actually three:
3. Since your package is relatively light, I think we can run all of the test suite, so should we? At least the python ones... Just let me know. We can definitely do that here :)

Sorry I didn't spot the problem earlier!

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by vsoch** [comment]
No worries, this looks great! And this bit:

> Would you like me to mark the previous builds as broken or even better retroactively fix the previous builds? We can do that. Just let me know and I will handle the logistics of that.

It would be fantastic to do either - marking the previous as broken or doing a global fix. Let me know what you'd like me to do / need help with, and if/when I should merge here.

**Comment by ngam** [comment]
This can be merged now. I will try to do a repropatch tomorrow to fix all previous builds by adding these constraints. I will tag you

**Pull request merged**
