### PR TITLE
Add vsoch + add tests?

### PR DESCRIPTION
**Pull request by ngam**
@vsoch (as per discussion in https://github.com/singularityhub/singularity-hpc/issues/464) I had some of these tests in earlier iterations, but there were issues here and there. I am happy to add them again in this pr to assess how best to approach this.

```yaml
    ## possible tests to run to ensure qc?
#     - pytest shpc/tests/test_settings.py  # [not win]
#     ## ignore linux test because test returns verbose value
# #     - pytest shpc/tests/test_utils.py  # [not linux64]
#     - pytest shpc/tests/test_container_config.py  # [not win] 
#     ## ignore othere tests because they trigger docker/singularity/podman
```

---

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by vsoch** [comment]
@ngam with respect to testing, my thinking for conda recipes is that the minimal test is just to do shpc --version (or version). Personally speaking I think shpc (at its repo) should be the main test runner - especially the tests here that require container technologies / lmod / modules that would need to be installed. We can't easily do that here.

**Comment by ngam** [comment]
> @ngam with respect to testing, my thinking for conda recipes is that the minimal test is just to do shpc --version (or version). Personally speaking I think shpc (at its repo) should be the main test runner - especially the tests here that require container technologies / lmod / modules that would need to be installed. We can't easily do that here.

Yes, that was exactly my rationale, see initial pr and discussion (with myself) here: https://github.com/conda-forge/staged-recipes/pull/17085

**Comment by ngam** [comment]
And especially that the build is pretty similar, etc. testing here wouldn't really be all that valuable. We usually like to do rigorous tests for more involved build --- did you know we build singularity/ce itself here too? I am also adding apptainer soon to stay up to date with the drama 🤦 

https://github.com/conda-forge/singularity-feedstock
https://github.com/conda-forge/singularityce-feedstock

**Comment by ngam** [comment]
@vsoch, are you cool then with me merging this or would you like to some more time to see if you'd like anything changed? Once merged, you will have the same access as me 😄

**Comment by vsoch** [comment]
I think it looks great - merge away!

**Pull request merged**
